development:
  exercise_service: http://localhost:3000
  submission_service: http://localhost:3001
  result_service: http://localhost:3002

test:
  exercise_service: http://localhost:3000
  submission_service: http://localhost:3001
  result_service: http://localhost:3002

production:
  exercise_service: <%= ENV['EXERCISE_URL'] %>
  submission_service: <%= ENV['SUBMISSION_URL'] %>
  result_service: <%= ENV['RESULT_URL'] %>